# terminal add socks5 proxy

alias setproxy='export ALL_PROXY=socks5://127.0.0.1:1086'
alias unsetproxy='unset ALL_PROXY'

# application alias

alias vs='open -a "Visual Studio Code"'
alias cc='git log -1 --pretty=format:%h | pbcopy'

