"set nocompatible              " be iMproved, required
filetype on " required
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
"set cindent

" completion

set completeopt=longest,menu

" strict

" close mouse
set mouse-=a

" 解决插入模式下delete/backspce键失效问题
set backspace=2

" close direction key
map <Left> <Nop>
map <Right> <Nop>
map <Up> <Nop>
map <Down> <Nop>

augroup markdown
    au!
    au BufNewFile,BufRead *.md,*.markdown setlocal filetype=ghmarkdown
augroup END

syntax on
set nu
set ai
set ruler

" vim-plug
call plug#begin('~/.vim/plugged')
Plug 'tomasr/molokai'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'vim-airline/vim-airline'
Plug 'jiangmiao/auto-pairs'
call plug#end()

map <F3> :NERDTreeMirror<CR>
map <F3> :NERDTreeToggle<CR>
